<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="Williams-MacBook-Pro.local" name="pytest" skipped="1" tests="3" time="0.060" timestamp="2020-02-19T11:38:22.066156"><testcase classname="tests.SimpleTest" file="tests.py" line="16" name="test_fail" time="0.001"><failure message="AssertionError: 11 != 10">self = &lt;tests.SimpleTest testMethod=test_fail&gt;

    def test_fail(self):
&gt;       self.assertEqual(11, 7 + 3)
E       AssertionError: 11 != 10

tests.py:18: AssertionError</failure></testcase><testcase classname="tests.SimpleTest" file="tests.py" line="13" name="test_pass" time="0.000"></testcase><testcase classname="tests.SimpleTest" file="tests.py" line="9" name="test_skipped" time="0.001"><skipped message="demonstrating skipping" type="pytest.skip">tests.py:10: demonstrating skipping</skipped></testcase></testsuite></testsuites>